<?php

/**
 * @file
 * Contains importexcel.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function importexcel_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the importexcel module.
    case 'help.page.importexcel':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Import Excel Calamari') . '</p>';
      return $output;

    default:
  }
}
